#!/usr/bin/env bash
ionic plugin rm com.ionic.keyboard ;
ionic plugin rm cordova-plugin-console  ;
ionic plugin rm cordova-plugin-crosswalk-webview ;
ionic plugin rm cordova-plugin-device ;
ionic plugin rm cordova-plugin-dialogs  ;
ionic plugin rm cordova-plugin-file-transfer   ;
ionic plugin rm cordova-plugin-geolocation  ;
ionic plugin rm cordova-plugin-media   ;
ionic plugin rm cordova-plugin-media-capture   ;
ionic plugin rm cordova-plugin-network-information ;
ionic plugin rm cordova-plugin-splashscreen   ;
ionic plugin rm cordova-plugin-whitelist    ;
ionic plugin rm io.github.pwlin.cordova.plugins.fileopener2 ;
ionic plugin rm org.apache.cordova.camera   ;
ionic plugin rm com.rde.cachemap    ;
ionic plugin rm com.ionic.deploy     ;
ionic plugin rm cordova-plugin-file  ;
ionic plugin rm org.apache.cordova.camera ;